baseURL = "https://cecastillo-1987.github.io/sala-del-lado/"
languageCode = "es"
title = "La sala del Lado"
theme = "anatole"
summarylength = 20
publishDir = "docs"

[params]
customCss = ["css/custom.css"]
title = "La sala del lado"
author = "La sala del lado"
description = "Blog de escrituras cinefilas."
profilePicture = "images/ruiz.jpeg"
favicon = "favicons/favicon.ico"
mainSections = ["posts"]
contentratio = 0.7
enableEmoji = true
displayMode = "dark"
disableThemeSwitcher = false
hidesidebar = false
reversepagetitle = true
disableTitleCapitalization = true
disableArchiveTitleStyling  = true
localizedDates = true
singleDateFormat = "2 de Enero de 2006"
indexDateFormat = "2 de Enero de 2006"
doNotLoadAnimations = true

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "Twitter"
url = "https://x.com/tu-usuario"

[[params.socialIcons]]
icon = "fab fa-instagram"
title = "Instagram"  # Cambiado de "Twitter"
url = "https://instagram.com/tu-usuario"

[menu]
  [[menu.main]]
  name = "Inicio"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Entradas"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "Colabora"
  weight = 300
  identifier = "about"
  url = "/about/"


  copyright = "2025-{{ YEAR }}"
